spring.application.name=eclosia-organization-service

server.port=8082

server.servlet.context-path=/api-organization

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5433/eclosia
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# KEYCLOAK / JWT
# ===============================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/eclosia


spring.cloud.gateway.discovery.locator.lower-case-service-id=true
logging.pattern.console=%boldGreen(%d{yyyy-MM-dd HH:mm:ss}) %-4relative [%boldMagenta(%thread)] [%highlight(%level)] %cyan(%-60logger{50}) : %boldGreen(%msg%n)
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.security=DEBUG
logging.levelorg.springframework.web.server.adapter.HttpWebHandlerAdapter=TRACE