spring.application.name=eclosia-organization-service

server.port=8082

spring.application.name=eclosia-organization-service

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5433/eclosia
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# KEYCLOAK / JWT
# ===============================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/eclosia